version: "3.9"
services:

  server:
    build:
      context: ./
      dockerfile: server.dockerfile
    ports:
      - 5000:5000
    environment:
      FLASK_ENV: development

  client:
    build:
      context:  ./client/reactapp/
      dockerfile: client.dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server